In [2]:
import os, sys
import sklearn
from sklearn.datasets import load_files
import pandas as pd
import numpy as np
import nltk
#stopwords = nltk.download('stopwords')
nltk.download('punkt')

from nltk.stem import PorterStemmer 
from nltk.tokenize import word_tokenize
import re
import nltk
import string
from nltk.corpus import stopwords
from os.path import join as pjoin
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn import svm
from sklearn import neighbors
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_score

os.makedirs( './data/' );
os.makedirs( './data/1/' );
os.makedirs( './data/0/' );

#load data
df = pd.read_csv("prePCSV.csv",encoding = 'latin1', names = ['date','title','2D-trend'])
stop_words = []

stop_words.extend(["sri","lanka","to","the","of","in","for","as","and","it","may","by","from","at","on","pct"])
#stop_words.append("lanka")

print(stop_words)

ps = PorterStemmer()

#pre-processing
def clean_str(istring):
    istring = re.sub(r"\n", "", istring)    
    istring = re.sub(r"\r", "", istring) 
    istring = re.sub(r"[0-9]", "", istring)
    istring = re.sub(r"\'", "", istring)    
    istring = re.sub(r"\"", "", istring)
    istring = re.sub('['+string.punctuation+']', '', istring)
    return istring.strip().lower()


print(df.shape[0])
for i in range(df.shape[0]):
    name = str (i)+ ".txt"  
    print(i)    
    if df.iloc[i,2] == '1':
        path_to_file = "./data/1/" + name
        FILE = open(path_to_file, "w")
        df.iloc[i,1] = clean_str(df.iloc[i,1])
        #print(df.iloc[i,1])
        words = word_tokenize(df.iloc[i,1])
        for w in words: 
            w = ps.stem(w)
            if w not in stop_words:
                #print(w)
                #w = w.encode('utf-8').strip()
                w = w.strip()
                print(w)
                FILE.write("%s " %w)
        FILE.close()
    elif df.iloc[i,2] == '0':
        path_to_file = "./data/0/" + name
        FILE = open(path_to_file, "w")
        df.iloc[i,1] = clean_str(df.iloc[i,1])
        #print(df.iloc[i,1])
        words = word_tokenize(df.iloc[i,1])
        for w in words: 
            #w = ps.stem(w)
            if w not in stop_words:
                w = w.strip()
                print(w)
                FILE.write("%s " %w)
        FILE.close()

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


['sri', 'lanka', 'to', 'the', 'of', 'in', 'for', 'as', 'and', 'it', 'may', 'by', 'from', 'at', 'on', 'pct']
4277
0
1
stock
close
down
rupe
new
low
2
stocks
end
up
3
shares
becalmed
despite
big
deals
4
sells
usmn
yr
bonds
5
rupee
new
low
6
consum
protect
activ
seen
weak
7
rupe
steadi
state
bank
sell
8
share
end
down
9
share
end
down
10
rupe
weaken
11
treasuri
yield
rise
12
expect
rupe
stabilis
below
dollar
13
credit
growth
import
demand
slow
central
bank
14
rupe
weaker
15
rupee
opens
weaker
16
mulls
yr
sovereign
bond
17
shares
end
up
18
exports
fall
january
trade
gap
up
19
warns
threat
eu
market
access
20
rupee
opens
firmer
against
dollar
21
shares
end
up
22
forex
reserv
down
jan
23
warn
against
subsidi
cultur
24
treasuri
yield
up
25
get
japanes
loan
airport
expans
26
vietnam
econom
potenti
explor
27
share
end
down
28
rupe
strengthen
credit
weaken
29
rupe
gain
after
open
30
share
becalm
31
seen
prioriti
destin
indian
invest
32
inflat
jump
march
33
track
get
imf
tranch
next
week
34
share

279
jkhaalka
rating
confirmed
280
lankas
cargills
ceylon
net
down
281
money
market
liquidity
dries
up
282
treasuries
yields
up
283
stock
close
up
284
stocks
down
285
stocks
up
rupee
weaker
286
stock
up
287
dairi
firm
eye
former
war
zone
export
288
india
up
health
sector
aid
289
treasuri
yield
up
290
singer
billion
rupe
debt
sale
ratedlka
291
stock
close
up
292
consumer
prices
rise
august
293
usmn
tower
block
india
group
have
storeys
294
stock
close
up
295
treasuri
bill
yield
up
296
stocks
close
up
297
business
forum
mekong
area
opportunities
sept
298
budget
deficit
gdp
first
half
299
stocks
up
over
two
weeks
300
stock
rally
takes
pause
301
treasuries
yields
flat
302
stocks
close
up
303
stocks
up
304
stocks
up
week
305
should
cut
corruption
opaque
rules
draw
investors
blake
306
sell
usmn
year
bond
307
economi
grow
q
statist
offic
308
bank
cricket
repair
imag
309
stock
down
310
keep
polici
rate
unchang
say
credit
slow
311
treasuries
yields
fall
312
stocks
close
one
percent
lower
313
push

510
commerci
credit
goe
second
tranch
511
forex
reserves
usbn
december
512
holds
policy
rates
amid
higher
inflation
513
drops
budget
support
loan
with
imf
514
sells
year
bonds
yield
515
war
zone
get
two
hospit
with
us
support
516
economi
grow
imf
517
will
be
forc
into
expens
loan
with
imf
out
legisl
518
invest
eye
polish
busi
519
treasuri
auction
yield
down
520
seek
usmn
world
bank
health
521
taxtak
weaken
amid
slowdown
exempt
imf
522
sells
us
million
floating
rate
bonds
523
rupee
weakens
amid
excess
liquidity
524
treasuries
yield
frozen
525
etisalat
creates
active
market
android
app
development
526
has
catch
up
english
literacy
undp
rep
527
urban
index
finds
prices
rising
over
year
528
forum
highlights
risks
ocean
resources
529
stock
slide
rupe
held
530
should
watch
debt
conting
liabil
imf
531
bond
yield
edg
up
532
doubl
pay
graduat
recruit
report
533
us
aid
continu
amid
hr
pressur
534
hospit
rate
confirm
ram
rate
535
inflat
februari
536
b
rate
confirm
s
p
amid
warn
537
treasuries
sli

799
adb
say
asian
nation
need
least
industri
be
rich
800
stock
slide
larg
cap
801
treasuri
yield
steadi
month
reject
802
sp
up
stake
malaysia
ram
rate
803
bond
yield
up
804
softlog
sell
a
billion
rupe
debt
805
bours
boost
secondari
debt
trade
806
nsb
bond
road
show
begin
aug
807
nsb
us
dollar
bond
rate
bb
fitch
808
nsb
dollar
bond
rate
bb
fitch
809
bond
yield
steadi
money
tighter
810
aim
high
becom
easier
place
busi
cb
governor
811
china
firm
seek
invest
power
wast
manag
812
helm
south
asia
free
trade
effort
813
rupe
weaker
bond
flat
814
unescap
boss
south
asia
econ
summit
815
rupe
fall
temporari
aberr
cb
governor
816
rupe
hit
new
low
817
treasuri
yield
steadi
818
lankas
softlogic
debentures
oversubscribed
819
spruce
up
two
cities
with
world
bank
finance
820
opposition
warns
foreign
borrowings
exchange
rate
821
inflat
up
august
822
rupe
under
moral
suasion
bond
eas
823
tighten
rule
car
import
amid
currenc
pressur
824
private
inflation
index
surges
july
825
forestry
case
826
forex
assoc

1042
narrows
policy
rate
corridor
1043
expects
growth
usbn
forex
reserves
1044
expect
growth
inflat
1045
year
sovereign
bond
sale
opens
report
1046
stocks
end
lower
1047
sells
one
billion
us
dollar
bond
1048
chambers
ask
probe
official
statistics
1049
stocks
close
up
1050
says
response
latest
bond
sale
shows
investor
confidence
1051
us
investors
buy
sovereign
bonds
report
1052
sovereign
bond
rated
pb
moodys
1053
sovereign
bond
rated
b
sp
1054
sovereign
bond
rated
bbexp
fitch
1055
stocks
surge
1056
treasuries
yields
drop
1057
giltbacked
yields
drop
ahead
auction
1058
stock
close
up
1059
new
year
sovereign
bond
price
will
help
privat
firm
standard
charter
1060
stocks
end
higher
1061
targets
usbn
fdi
1062
stocks
up
corrected
1063
stocks
up
1064
interest
rates
tighter
ahead
dollar
inflow
1065
stocks
down
1066
stocks
close
up
1067
srilankan
airlines
seeks
usmn
foreign
financing
1068
stocks
close
flat
1069
malaysias
ram
exits
rating
agency
1070
stocks
close
up
1071
arrest
fugit
politician
ov

bank
credit
subdu
data
1326
stock
close
up
1327
stock
close
up
1328
share
close
down
1329
ceylon
cold
store
net
up
june
quarter
1330
india
mutual
forex
reserv
invest
pact
1331
cricket
steyn
strike
earli
second
test
1332
share
close
lower
1333
debt
interest
cost
among
highest
world
moodi
1334
imf
cut
global
growth
forecast
see
rise
risk
1335
share
close
higher
1336
rate
agenc
tie
up
with
crisil
india
1337
share
close
higher
1338
share
close
up
1339
launch
dollar
mutual
fund
draw
foreign
investor
1340
treasuri
yield
plung
four
decad
low
1341
first
dollar
bond
fund
rate
bb
fitch
1342
caution
foreign
borrow
imf
inflat
watch
urg
1343
stock
close
up
1344
inflat
acceler
juli
1345
stocks
close
lower
1346
lankas
uda
sell
rsbn
listed
debt
1347
stocks
close
up
1348
stocks
close
down
1349
stocks
close
up
1350
stock
close
up
1351
stock
close
up
1352
debt
profil
improv
midyear
central
bank
1353
pave
a
road
with
an
invest
mn
1354
stock
close
up
1355
share
close
up
1356
slam
us
over
travel
warn
1357
s

govern
tax
individu
car
import
1542
treasuri
bill
yield
flat
central
bank
1543
financ
minist
justifi
mansion
tax
1544
generate
revenue
though
taxes
not
printing
money
deputy
minister
economy
1545
lankas
policy
going
forward
not
what
you
see
deputy
affairs
minister
1546
lankas
pm
calls
unity
harmony
among
communities
going
forward
1547
chamber
chief
says
not
all
private
sector
cos
have
illgotten
gains
1548
sealed
strausskahn
deal
1549
lankas
port
city
project
go
ahead
china
get
land
minister
1550
lankas
economic
relations
with
india
play
a
crucial
role
making
island
an
economic
hub
chamber
ceo
1551
revises
mansion
tax
rules
report
1552
lankas
senior
appointments
be
decided
constitutional
council
deputy
policy
planning
1553
boi
compani
not
exempt
super
gain
taxat
govern
1554
treasuri
bill
yield
up
1555
aitken
spenc
decemb
net
down
1556
attract
indian
invest
1557
cargil
get
usmn
ifc
invest
1558
insur
get
a
new
chairman
1559
softlog
decemb
net
up
1560
treasuri
bill
yield
up
central
bank
15

1711
inflat
stabl
april
1712
stock
close
up
1713
develop
a
new
polici
invest
boi
chief
1714
boi
undergo
cultur
think
pattern
chang
up
invest
1715
maintain
midsingl
digit
inflat
level
till
end
central
bank
1716
should
strive
better
balanc
between
social
develop
wealth
creation
economist
1717
stock
close
up
1718
invest
stock
market
is
riski
busi
ceylon
tobacco
compani
1719
treasuri
bill
yield
drop
central
bank
1720
treasuri
bill
yield
drop
central
bank
1721
stock
close
down
1722
cd
host
region
train
seminar
depositori
1723
stock
close
up
1724
talk
with
adb
doubl
annual
fund
bn
1725
export
up
feb
import
rise
a
faster
1726
stock
close
flat
1727
stock
close
higher
1728
treasuri
ha
adequ
fund
pay
govt
employe
financ
minist
1729
sell
rsbn
year
bond
year
bond
reject
1730
stock
close
up
1731
be
par
with
region
cd
next
yr
cd
head
1732
busi
chamber
welcom
govt
initi
eas
do
busi
1733
ceylon
tobacco
sale
up
increas
dispos
incom
interim
report
1734
fitch
assign
singer
debentureslka
final
rate
1735
s

1887
govern
foreign
borrow
rsbn
rsbn
borrow
1888
central
bank
confid
growth
will
pick
up
q
more
privat
invest
after
elect
1889
central
bank
appoint
a
new
member
monetari
board
1890
plantat
associ
say
adequ
replant
rate
maintain
tea
rubber
1891
cb
governor
say
i
wa
not
deal
roomreject
cope
alleg
1892
stock
close
down
week
low
1893
stock
market
up
april
report
1894
probe
into
tsunami
relief
vehicl
1895
export
us
rise
with
renew
gsp
ministri
industri
commerc
1896
month
treasuri
bill
yield
up
central
bank
1897
stock
close
down
jkh
lower
1898
increas
tax
tobacco
alcohol
product
next
budget
1899
lankas
growth
rate
numbers
reduced
last
two
years
with
new
base
year
change
1900
fitch
ratings
corrects
lankas
usd
bond
bbexp
1901
projects
have
be
reassessed
reflect
realistic
numbers
with
gdp
change
harsha
1902
stocks
close
up
jkh
gains
1903
sells
rs
bn
year
bonds
1904
fitch
ratings
host
investment
fund
asset
management
forum
1905
lankas
asiri
central
hospitals
sells
horton
place
land
rsbn
1906
sto

2068
nestl
continu
rs
bn
invest
plan
compli
with
list
rule
2069
stock
close
down
profit
take
2070
coca
cola
resum
oper
will
pay
compens
cea
2071
global
market
plung
weak
china
factori
data
2072
account
bodi
urg
govt
maintain
publish
account
2073
kalpitiya
beach
resort
say
new
plan
track
2074
stock
close
down
2075
treasuri
bill
yield
up
year
up
bp
2076
asia
sme
need
more
growth
capit
be
competit
adb
2077
asian
stock
up
china
take
long
weekend
break
2078
govt
must
be
consist
speak
with
one
voic
pathfind
foundat
2079
gear
up
period
continu
growth
softlog
stockbrok
2080
receiv
usd
bn
under
rbi
swap
arrang
central
bank
governor
2081
eden
hotel
rais
rsbn
through
right
issu
2082
stock
close
higher
net
foreign
outflow
2083
fitch
maintain
ceylon
incom
fund
rate
watch
neg
2084
updat
central
bank
interven
less
forex
sourc
2085
bank
ceylon
sell
rs
bn
debt
aa
rate
2086
hnb
senior
subordin
debt
get
aa
a
rate
fitch
2087
stock
close
down
low
investor
activ
2088
new
financ
minist
say
wont
allow
artific

accounting
body
calls
fiscal
consolidation
2274
stocks
close
up
2275
janashakthi
seals
aias
general
insurance
business
acquisition
2276
indias
sandal
lands
mulls
usd
mn
fdi
lankas
real
estate
2277
growth
moderating
new
equilibrium
currency
2278
central
banks
use
negative
interest
rates
stimulus
2279
ptl
watch
cbsl
sells
more
than
rs
bn
bonds
demand
builds
2280
stocks
close
flat
six
week
low
2281
fitch
assigns
sampath
banks
subordinated
debt
finallka
2282
treasury
bond
auction
rs
bn
bids
accepted
2283
lankas
rupee
is
way
over
sold
says
technical
analyst
2284
budget
should
signal
revenue
generation
reforms
economist
2285
raises
usdbn
sovereign
bond
issue
report
2286
watawala
plantation
profits
up
palm
oil
supports
bottomline
2287
ranked
ease
doing
business
index
2288
treasury
bill
yields
down
2289
ptl
watch
sovereign
bond
attracts
local
investors
bonds
2290
stocks
close
up
institutional
buying
2291
lankas
sovereign
bond
issue
oversubscribed
times
central
bank
2292
incom
secur
older
perso

2471
ptl
watch
bond
yields
climb
after
auction
2472
gdp
grows
third
quarter
census
dept
2473
ptl
watch
yields
tick
higher
tbill
yields
up
2474
sp
dow
jones
announces
changes
sp
index
2475
us
fed
raises
rates
bp
first
hike
since
2476
if
required
mr
able
sell
mihin
air
one
rupee
eran
2477
ptl
watch
little
activity
ahead
bond
auction
2478
we
are
not
dictated
imf
policy
finance
minister
2479
requests
india
extend
usd
bn
swap
facility
one
year
2480
turkey
provide
usdmn
development
projects
2481
can
not
expect
imf
come
sort
out
problems
razeen
sally
2482
president
controls
smaller
share
govt
expenditure
manthrilk
2483
ptl
watch
yield
curve
up
after
bond
auction
2484
motor
car
registrations
high
november
jb
securities
2485
stock
close
lower
five
month
low
â
2486
ptl
watch
thin
activ
tbill
yield
increas
2487
colombo
port
will
have
troubl
provid
welfar
facil
employe
minist
2488
inflat
acceler
novemb
2489
ptl
watch
littl
bond
activ
omo
absorb
excess
liquid
2490
finlay
get
regul
nod
delist
2491
s

lankas
megapolis
plan
a
challenge
needs
experts
make
successful
2671
go
market
after
imf
meet
2672
investrust
say
money
market
fund
outperform
2673
popular
intern
stock
take
a
beat
say
analyst
2674
potenti
imf
fund
help
fiscal
consolid
moodi
2675
ptl
watch
yield
climb
with
bond
auction
2676
colombo
inflat
acceler
februari
2677
seylan
bank
net
profit
up
percent
full
year
2678
fitch
downgrad
rate
b
extern
debt
2679
find
more
hidden
due
past
regim
ravi
karunanayak
2680
bodi
shop
launch
2681
us
call
join
indopacif
econom
corridor
2682
central
bank
sell
usdmn
worth
develop
bond
2683
china
posit
trade
invest
say
malik
after
visit
2684
ptl
watch
bond
yield
tick
higher
thin
volum
2685
singer
rais
rsbn
list
debt
2686
china
eagerli
wait
pm
visit
boi
2687
stock
exchang
launch
educ
web
portal
2688
export
import
declin
trade
gap
widen
decemb
2689
stock
close
lower
2690
ptl
watch
lacklust
trade
some
foreign
sell
bond
2691
brent
oil
up
iron
ore
up
commod
ralli
2692
ptl
watch
sell
bond
2693
lirneasia


year
sovereign
bond
issue
2869
exports
imports
decline
trade
gap
shrinks
february
2870
asian
shares
near
six
week
high
oil
fed
expectations
2871
ptl
watch
bond
yields
steady
low
volumes
2872
australian
miner
drill
mineral
samples
puttalam
2873
approves
funds
reservoirs
southern
roads
2874
ptl
watch
yields
drop
after
treasury
bond
auction
2875
introduce
capital
gains
tax
remove
exchange
control
pm
2876
imf
confirms
has
additional
rs
trillion
liabilities
2877
ptl
watch
volatility
returns
some
foreign
buying
2878
lankan
rupee
up
exporters
foreign
investors
convert
dollars
2879
asian
shares
sterling
skid
yen
firms
2880
brexit
vote
wont
favor
risk
assets
gross
2881
ifc
looks
fund
infrastructure
tourism
energy
2882
bitcoin
hits
year
high
now
chinese
buying
2883
ptl
watch
yields
tick
higher
foreign
holding
up
2884
adb
sign
usdmn
grant
flood
landslide
relief
2885
sells
usdmn
oneyear
development
bonds
2886
oil
futur
fall
global
growth
brexit
concern
weigh
2887
foreign
reserv
usd
billion
end
288

3029
lankas
exports
lagging
asia
governor
3030
expectations
economic
management
not
being
met
razeen
sally
3031
implementation
delivery
execution
key
malaysias
pemandu
ceo
3032
lankas
private
sector
being
too
risk
averse
finance
minister
3033
forging
ahead
with
reforms
intraasia
trade
pm
3034
ptl
watch
bond
yields
ease
further
foreign
buying
3035
introduce
public
enterprise
act
next
month
malik
3036
distilleries
share
swap
gets
court
go
ahead
3037
boe
rate
call
looms
asian
shares
firm
oil
rebounds
now
3038
nihal
fonseka
appointed
monetary
board
3039
jb
vantage
wins
cfas
top
unit
trust
award
3040
lankan
rupee
up
bond
buying
foreigners
spot
starts
trading
3041
etca
first
round
negotiations
starts
soon
indian
high
commissioner
3042
asia
gains
boe
easing
boon
key
us
jobs
data
awaited
3043
central
bank
reforms
bond
trading
3044
colombo
stock
exchange
offers
online
services
through
cds
econnect
3045
malaysias
rationalization
soes
lessons
3046
japans
sbi
group
acquire
stake
first
guardian
equ

stock
up
3197
asian
stock
hold
near
month
peak
fed
relief
3198
adb
give
usdmn
transport
feasibl
studi
3199
ptl
watch
bond
yield
mostli
lower
bp
3200
imf
mission
say
delay
vat
law
postpon
review
3201
lankan
share
up
third
straight
session
blue
chip
3202
asian
shares
slip
us
presidential
debate
awaited
3203
fund
flows
into
emerging
markets
threeyear
high
3204
lankan
rupee
slips
seasonal
importer
dollar
demand
3205
poll
cb
stand
pat
this
wk
assessing
impact
previous
hikes
3206
asia
stocks
slip
yen
gains
us
debate
jitters
3207
lankan
rupee
weaker
importer
dollar
demand
3208
ptl
watch
bond
yields
drop
local
investor
buying
3209
central
bank
holds
key
interest
rates
unchanged
3210
asia
stocks
inch
up
after
wall
streets
gains
oil
prices
slide
3211
see
usd
bln
investments
india
etca
discussed
minister
3212
adb
lowers
growth
3213
cb
governor
says
q
growth
should
be
higher
than
3214
asia
stocks
gains
crude
oil
surges
after
opec
deal
3215
lankan
rupee
edge
down
ahead
bond
auction
3216
can
meet
bu

3389
opinion
chang
natur
work
necessit
a
univers
basic
incom
3390
dollar
steadi
with
bond
oil
anxiou
about
opec
3391
asian
market
mix
decemb
rate
hike
eye
3392
monetary
board
holds
interest
rates
unchanged
3393
budget
deficit
narrows
first
nine
months
cb
3394
cctv
new
auction
system
among
steps
strengthen
bond
trading
cb
3395
lankan
rupee
edges
down
importer
dollar
demand
stx
up
3396
lankas
budget
headed
right
direction
imf
3397
asia
stocks
edge
up
us
growth
data
cues
dollar
steady
3398
tourist
earnings
up
slower
growth
workers
remittancesâ
3399
lankas
budget
under
president
3400
challenging
external
environment
wb
economist
3401
lankan
rupee
edges
up
exporter
dollar
sales
stx
up
3402
lankas
ccpi
inflation
down
nov
3403
asia
flat
following
a
weaker
wall
street
treasury
yields
hit
mth
high
3404
oil
dollar
bond
yields
sharply
higher
after
opec
deal
3405
lankan
rupee
eases
importer
dollar
demand
stx
up
3406
lankan
rupee
gains
exporter
dlr
sales
subdued
importer
demand
3407
asia
stock
fund

central
bank
holds
policy
interest
rates
unchanged
3576
ptl
watch
bond
yields
mostly
lower
after
rate
stance
3577
nikkei
edges
down
choppy
trade
glass
sector
outperforms
3578
government
finland
keen
invest
3579
ptl
watch
bond
yields
mixed
more
foreign
selling
3580
lankas
external
situation
manageable
but
more
fdi
needed
governor
3581
cope
reveals
rsbn
loss
public
institutions
3582
haycarb
records
turnover
rsbn
pbt
rsmn
q
3583
fitch
affirms
b
outlook
revised
stable
3584
ptl
watch
bond
yields
slightly
lower
credit
rating
3585
yen
slips
after
trumpabe
meet
asian
shares
firm
3586
imf
worried
about
elections
europe
populist
candidates
3587
foreign
reserves
drop
usdmn
january
3588
asia
shares
notch
month
highs
dollar
firm
3589
south
asian
stock
exchange
officials
meet
colombo
3590
hayleys
q
profits
grow
rsbn
3591
more
publicpriv
collabor
need
dure
humanitarian
crise
wef
3592
senior
citizen
deposit
up
rsmn
get
higher
interest
3593
asian
stock
year
high
robust
wall
st
dollar
retreat
3594
with


3764
obtain
usdmn
loan
pakistan
3765
sunshine
holdings
records
strong
growth
despite
challenging
market
condition
revenue
up
3766
opinion
building
future
infrastructure
asean
south
asia
3767
dilmah
expolanka
support
lkis
global
economy
programme
3768
vehicle
registrations
drop
april
jb
securities
3769
video
show
rice
contain
plastic
is
fals
ministri
3770
growth
acceler
world
bank
3771
central
bank
denies
banks
stopped
accepting
qatari
riyals
3772
ptl
watch
treasury
bond
yields
mixed
3773
trade
gap
widen
march
3774
lankan
bank
like
come
under
capit
pressur
basel
iii
fitch
3775
ha
been
live
beyond
mean
governor
3776
sign
strateg
econom
partnership
with
thailand
august
3777
treasuri
issu
rsbn
guarante
3778
former
lankan
president
warns
dont
be
misled
gsp
benefits
3779
odel
softlogic
brands
buys
space
colombo
city
centre
3780
obtains
usdbn
foreign
loans
china
leads
3781
dfcc
subscribes
commercial
bank
rights
issue
full
3782
us
rate
hike
expected
hit
borrowers
eyes
equities
3783
lankas
fina

3971
cse
renam
default
board
watch
list
3972
extern
pressur
constrain
credit
profil
moodi
3973
export
up
trade
deficit
widens
3974
pakistan
open
consultation
after
years
targets
usbn
trade
3975
target
usdbn
fdi
per
year
per
capita
incom
usd
pm
3976
pm
introduc
liabil
mgmt
fund
fund
be
rais
with
transpar
3977
cse
host
nasdaq
market
site
3978
mastercard
opensup
access
blockchain
api
partner
bank
merchant
3979
get
usdmn
saudi
fund
develop
3980
budget
promis
mostli
conceal
or
breach
research
3981
over
lankan
tax
file
holders
hide
true
income
3982
securities
exchange
act
be
presented
parliament
3983
cse
conduct
national
survey
understand
public
share
investments
3984
lankas
port
city
completes
phase
one
land
reclamation
minister
3985
port
city
phase
two
eia
public
comments
next
month
3986
german
companies
invested
usdmn
boi
3987
boost
bilater
tie
with
qatar
seek
partnership
nation
carrier
3988
seylan
bank
record
profitaftertax
rsbn
q
3989
should
use
technolog
promot
transpar
effici
busi
399

4159
virtusa
says
businesses
plan
invest
digital
transformation
4160
govt
ensure
continued
progress
financial
inclusion
fin
min
4161
pledges
support
commonwealth
small
states
trade
finance
facility
4162
imposes
tax
gold
imports
4163
will
ensure
resource
utilization
sustainable
manner
president
4164
richard
pieris
finance
merge
with
chilaw
finance
4165
laugfs
leaders
excel
cmi
management
excellence
awards
4166
capacity
building
manage
public
debt
liability
is
need
hour
eran
4167
foreign
reserves
fall
usdbn
march
4168
inflation
slows
march
lowest
since
april
4169
cse
requests
clients
barred
broker
firms
transfer
their
stocks
4170
laugfs
excel
cmi
management
excellence
awards
4171
ntb
launch
open
api
banking
4172
chinas
massive
obor
hub
asia
bullish
fta
4173
galle
face
properties
commence
construction
renuka
tower
4174
rupee
falls
record
low
4175
central
bank
rejects
bandulas
claim
lack
funds
pay
off
tbonds
4176
budget
promises
near
completion
broken
research
4177
presidential
commission


In [6]:
dir = r'./data'
# loading all files as training data. 
text_data = load_files(dir, encoding = 'latin1', shuffle=True)
# target names ("classes") are automatically generated from subfolder names

# Initialize a CoutVectorizer to use NLTK's tokenizer instead of its 
# default one (which ignores punctuation and stopwords). 
# initialize data_vector object, and then turn movie train data into a vector
data_vec = CountVectorizer(min_df=2, tokenizer=nltk.word_tokenize)  
data_counts = data_vec.fit_transform(text_data.data)

tfidf_transformer = TfidfTransformer()
data_tfidf = tfidf_transformer.fit_transform(data_counts)
# Same dimensions, now with tf-idf values instead of raw frequency count

# 1    576
# 0    576
# Name: balance, dtype: int64

#Uncomment below section to test with different classifiers and test accuracies

docs_train, docs_test, y_train, y_test = train_test_split(data_tfidf, text_data.target, test_size = 0.25, random_state = 12)
docs_train, docs_val, y_train, y_val = train_test_split(docs_train, y_train, test_size = 0.1, random_state = 12)
 
print(docs_train[1].shape)


print('DecisionTreeClassifier')
clf = tree.DecisionTreeClassifier().fit(docs_train, y_train)
y_pred = clf.predict(docs_test)
print(sklearn.metrics.accuracy_score(y_test, y_pred))
cm = confusion_matrix(y_test, y_pred)
print(cm)
# 10 fold CV
clf = tree.DecisionTreeClassifier()
scores = cross_val_score(clf, data_tfidf, text_data.target, cv=10)
print (scores) # Results for all the folds
print ("10CV Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(),scores.std()*2))


print('NeighborsClassifier')
clf = neighbors.KNeighborsClassifier(n_neighbors=1).fit(docs_train, y_train)
y_pred = clf.predict(docs_test)
print(sklearn.metrics.accuracy_score(y_test, y_pred))
cm = confusion_matrix(y_test, y_pred)
print(cm)
# 10 fold CV
clf = neighbors.KNeighborsClassifier(n_neighbors=1) 
scores = cross_val_score(clf, data_tfidf, text_data.target, cv=10)
print (scores) # Results for all the folds
print ("10CV Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(),scores.std()*2))


print('MultinomialNB')
clf = MultinomialNB().fit(docs_train, y_train)
y_predNB = clf.predict(docs_test)
print(sklearn.metrics.accuracy_score(y_test, y_predNB))
cm = confusion_matrix(y_test, y_predNB)
print(cm)
# 10 fold CV
clf = MultinomialNB()
scores = cross_val_score(clf, data_tfidf, text_data.target, cv=10)
print (scores) # Results for all the folds
print ("10CV Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(),scores.std()*2))


print('SVM')
clf = svm.SVC(kernel='linear', C=1,gamma=1).fit(docs_train, y_train)
y_pred = clf.predict(docs_test)
print(sklearn.metrics.accuracy_score(y_test, y_pred))
cm = confusion_matrix(y_test, y_pred)
print(cm)
# 10 fold CV
clf = svm.SVC(kernel='linear', C=1,gamma=1)
scores = cross_val_score(clf, data_tfidf, text_data.target, cv=10)
print (scores) # Results for all the folds
print ("10CV Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(),scores.std()*2))

# clf = svm.SVC(kernel='linear', C=1,gamma=1).fit(data_tfidf, text_data.target)
# df_test = pd.read_csv("testsetwithoutlabels.csv", names = ['heading','date','text'])


from keras import models
from keras import layers
from keras.utils import to_categorical
from keras import backend as K

from keras.optimizers import SGD

opt = SGD(lr=0.00000005)


def root_mean_squared_error(y_true, y_pred):
        return K.sqrt(K.mean(K.square(y_pred - y_true)))
    
print(docs_train.shape)

docs_train = docs_train.toarray().reshape(2886,1,2319)
docs_val = docs_val.toarray().reshape(321,1,2319)
print(y_train.shape)
#y_train = y_train.reshape(3275,1)
print(docs_train)
#for x in y_train:
    #print(x)
print(y_train.shape)
print(docs_train.shape)

from keras.regularizers import L1L2

def custom_activation(x):
    return x*100;

network = models.Sequential()
network.add(layers.Dense(units=10, activation=custom_activation, input_shape=(docs_train.shape[1],docs_train.shape[2],), bias_regularizer=L1L2(l1=0.01, l2=0.001)))
#network.add(layers.Dense(64, activation=custom_activation))
#network.add(layers.Dense(32, activation='relu'))
#network.add(layers.Dense(10, activation=custom_activation))
network.add(layers.Dense(1, activation='sigmoid'))

network.compile(optimizer=opt,loss = root_mean_squared_error, metrics=['accuracy'])



network.fit(docs_train, y_train, epochs=10,validation_data=(docs_val, y_val), batch_size=20)

p_stock_price = network.predict(docs_test.toarray().reshape(1069,1, 2319), batch_size = 20)



(1, 2319)
DecisionTreeClassifier
0.8568755846585594
[[442  87]
 [ 66 474]]
[0.88578089 0.91142191 0.86682243 0.89252336 0.90632319 0.87822014
 0.87587822 0.86651054 0.85245902 0.83138173]
10CV Accuracy: 0.88 (+/- 0.05)
NeighborsClassifier
0.6735266604303087
[[503  26]
 [323 217]]
[0.69463869 0.68298368 0.6635514  0.6682243  0.71896956 0.67915691
 0.71428571 0.6557377  0.72131148 0.70960187]
10CV Accuracy: 0.69 (+/- 0.05)
MultinomialNB
0.9429373246024322
[[481  48]
 [ 13 527]]
[0.95571096 0.95804196 0.95327103 0.97663551 0.95081967 0.94613583
 0.95550351 0.95316159 0.95784543 0.93676815]
10CV Accuracy: 0.95 (+/- 0.02)
SVM
0.9354536950420954
[[473  56]
 [ 13 527]]
[0.94638695 0.96969697 0.93691589 0.96962617 0.94379391 0.94613583
 0.96018735 0.93442623 0.93676815 0.93442623]
10CV Accuracy: 0.95 (+/- 0.03)
(2886, 2319)
(2886,)
[[[0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0.

In [7]:
import numpy
val = []
for p in p_stock_price:
    print(p)
    if(p>0.9):
        p = 1
    else:
        p = 0
    val.append(p)
    
    
#val.toarray().reshape(1223)
arr = numpy.array(val) 
    


[[0.00376865]]
[[0.71560776]]
[[0.23148248]]
[[0.00073799]]
[[0.78678685]]
[[0.02733809]]
[[0.01917967]]
[[0.01885897]]
[[0.5310839]]
[[0.00168562]]
[[0.82792354]]
[[0.00213337]]
[[0.00527373]]
[[0.02177584]]
[[0.7631213]]
[[0.00150347]]
[[0.00205736]]
[[0.7489637]]
[[0.98527133]]
[[0.31159604]]
[[0.4873339]]
[[0.09096906]]
[[0.9753823]]
[[0.02265549]]
[[0.00175652]]
[[0.3767352]]
[[0.9875014]]
[[0.06331471]]
[[0.516395]]
[[0.6584879]]
[[0.23933348]]
[[0.23933348]]
[[0.03078467]]
[[0.19732404]]
[[0.96287143]]
[[0.5307706]]
[[0.00199793]]
[[0.03911242]]
[[0.5211766]]
[[0.9654028]]
[[0.6736684]]
[[0.6531677]]
[[0.6431283]]
[[0.2797823]]
[[0.00161323]]
[[9.801984e-05]]
[[0.88647723]]
[[0.08890724]]
[[0.34090808]]
[[0.0115737]]
[[0.00107199]]
[[0.23933348]]
[[0.9874163]]
[[0.51752055]]
[[0.00864494]]
[[0.8955526]]
[[0.9051875]]
[[0.9991315]]
[[0.01530425]]
[[0.47335553]]
[[0.99732697]]
[[0.9966334]]
[[0.9465605]]
[[0.02661708]]
[[0.09920043]]
[[0.9972048]]
[[0.00037345]]
[[0.39438692]]
[[0

[[0.7510261]]
[[0.0474987]]
[[0.098667]]
[[0.25375322]]
[[0.07292202]]
[[0.286444]]
[[0.99686]]
[[0.9879776]]
[[0.9999352]]
[[0.9992292]]
[[0.00085041]]
[[0.00094792]]
[[0.05135876]]
[[0.6641007]]
[[0.00505245]]
[[0.6075493]]
[[0.03485032]]
[[0.9774425]]
[[0.6710868]]
[[0.8527701]]
[[0.00111097]]
[[0.58010036]]
[[0.00013876]]
[[0.9872806]]
[[0.00566345]]
[[0.01595917]]
[[0.08629447]]
[[0.11305225]]
[[0.06476346]]
[[0.9917865]]
[[0.9707939]]
[[0.8552353]]
[[0.9648541]]
[[0.01007912]]
[[0.9625292]]
[[0.79468304]]
[[0.25932544]]
[[0.9110119]]
[[0.99359554]]
[[0.2502742]]
[[0.8950025]]
[[0.73496455]]
[[0.99809515]]
[[0.06584758]]
[[0.9975773]]
[[0.04003671]]
[[0.27451742]]
[[0.31399155]]
[[0.9964295]]
[[0.71485084]]
[[0.33963972]]
[[0.00663823]]
[[0.98511016]]
[[0.07950619]]
[[0.9849143]]
[[0.00270581]]
[[0.2502742]]
[[0.50307965]]
[[0.9905566]]
[[0.9973834]]
[[0.00153732]]
[[0.25027418]]
[[0.98691404]]
[[0.5118962]]
[[0.15791613]]
[[0.74677336]]
[[0.00017089]]
[[0.13551933]]
[[0.9639516]]

In [8]:
from sklearn.metrics import accuracy_score

print(arr)

print("Accuracy for trend prediction:", accuracy_score(y_test, arr))



[0 0 0 ... 1 0 0]
Accuracy for trend prediction: 0.4667913938260056


In [9]:
i = 0
for p in y_test:
    print(p, ' ', y_predNB[i])
    i = i+1

0   0
0   0
1   1
1   1
0   0
1   1
1   1
1   1
0   0
1   1
1   1
1   1
1   1
0   0
1   1
1   1
1   1
0   0
1   1
0   0
1   1
0   0
1   1
1   1
1   1
0   0
0   0
0   0
1   1
1   1
1   1
1   1
0   0
0   0
0   0
0   0
1   1
1   1
0   0
1   1
1   1
1   1
1   0
1   1
0   0
1   1
0   0
1   0
1   1
0   0
1   1
1   1
1   1
1   1
0   0
1   1
0   0
0   0
1   1
1   1
1   1
0   0
0   0
0   0
0   0
0   0
1   1
0   0
1   1
1   1
1   1
1   1
1   1
0   0
0   0
1   1
0   1
1   1
1   1
0   0
1   1
0   0
1   1
0   0
0   0
1   1
1   1
0   0
1   1
0   1
0   0
0   0
1   1
0   0
0   0
1   1
1   1
1   1
1   0
1   1
1   1
0   0
1   1
0   0
0   0
0   1
0   0
1   1
0   0
1   1
1   1
0   0
1   1
1   1
0   0
0   0
0   0
1   1
1   1
0   0
1   1
0   0
1   1
0   0
0   0
0   0
0   0
1   1
0   0
1   1
1   1
0   0
1   0
1   1
1   1
0   0
1   1
0   0
1   1
1   1
0   0
1   1
1   1
0   1
0   0
1   1
0   0
0   1
1   1
0   0
0   0
0   0
0   0
0   1
1   1
1   1
1   1
1   1
0   1
1   1
1   1
1   1
1   1
0   0
1   1
0   1
1   